name: HestiaStay Mobile Tests

on:
push:
branches:
- main

pull_request:
branches:
- main

jobs:
automation-tests:
runs-on: windows-latest

```
steps:
  - name: Checkout Repository
    uses: actions/checkout@v4

  - name: Setup Python
    uses: actions/setup-python@v5
    with:
      python-version: "3.12"

  - name: Install Dependencies
    run: |
      python -m pip install --upgrade pip
      pip install pytest
      pip install pytest-html
      pip install Appium-Python-Client

  - name: Verify Pytest Installation
    run: |
      pytest --version
```
